### ISSUE TITLE
Being able to chose a number of sms to send

### ISSUE THREAD

**Issue by ghost** [tiphedor/SMS-Spammer-Android#1]

**Comment by tiphedor** [comment]
Not sure i understood this one, you can either type a number or pick a contact, isn't it enough ? Do you have another idea ?

**Comment by ghost** [comment]
Sorry, I should have given more details.
No I mean being able to choose to send 10 messages, 86 messages. Having an option that allow to send a certain number or not

**Comment by tiphedor** [comment]
Added in 84a3af64b2 .
Release here : https://github.com/tiphedor/SMS-Spammer-Android/releases/tag/1.2

Thanks for suggesting :)

**Comment by ghost** [comment]
No problem, I like to help :)
