### ISSUE TITLE
Knowing more easily if sms are being sent or not

### ISSUE THREAD

**Issue by ghost** [tiphedor/SMS-Spammer-Android#2]
Right now when you click start or stop there is no change so you can't be sure if there is message going or not.
Having a graphical change or something like that could help being sure you've done what you wanted

**Comment by tiphedor** [comment]
Fixed in ff3572c9a5 
Thanks for the suggestion. 

(APK available : https://github.com/tiphedor/SMS-Spammer-Android/releases/tag/1.1 )
