### ISSUE TITLE
Small change to the name

### ISSUE THREAD

**Issue by ghost** [tiphedor/SMS-Spammer-Android#4]
Only an esthetic change, not really important ^^
Right now the name is like that:

![first](https://cloud.githubusercontent.com/assets/7694864/6001099/30b8e71c-aae6-11e4-9823-5e2691d1216c.png)

Maybe putting spammer below sms would make it clearer.
![first](https://cloud.githubusercontent.com/assets/7694864/6001151/b17e9d06-aae6-11e4-976d-004502aa28dd.png)

**Comment by tiphedor** [comment]
Check if 297fdd9d1c solved this ;)
