### ISSUE TITLE
Update versionCode

### ISSUE THREAD

**Issue by ghost** [tiphedor/SMS-Spammer-Android#5]
Please update versionCode and versionName. Look at your app/build.gradle:

```
versionCode 1
versionName "1.0"
```

The versionName is just a fancy string, but the versionCode is an integer that is used to check if an updated version is available. See https://developer.android.com/tools/publishing/versioning.html .

**Comment by tiphedor** [comment]
Yup, sounds like i forget to update it.

45405d1cd303eeb429fbfea9d9357a3f7cc800fb
