### ISSUE TITLE
Can a simple function be added? 

### ISSUE THREAD

**Issue by ghost** [tiphedor/SMS-Spammer-Android#6]
Is it possible to add the option to add a delay in seconds between each SMS?

**Comment by tiphedor** [comment]
If I have a minute someday, I'll take a look

**Comment by OpenSourceIsCool** [comment]
When do you expect it to release? I think I can create a delay timer and some other features.

**Comment by tiphedor** [comment]
Feel free to open a pull request if you do have time, I'll be happy to check it out !

M.

Le 7 d?c. 2015 ? 01:18, OpenSourceIsCool <notifications@github.com<mailto:notifications@github.com>> a ?crit :

When do you expect it to release? I think I can create a delay timer and some other features.

##

**Comment by OpenSourceIsCool** [comment]
Cool, thanks!
https://www.avast.com/?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
https://www.avast.com/?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
