### ISSUE TITLE
limit the messages / min to 200

### ISSUE THREAD

**Issue by arch-user-france1** [tiphedor/SMS-Spammer-Android#7]
well not available on playstore anymore? Well the store for the /e/ OS (www.e.foundation) has it...

The problem is there is a limit of (you can set it to maximum 200 messages and can't put it off) 200 messages per minute. The problem is your app doesn't have that.

Could you add it? Thanks... Just like make settings

PS: a mass-spammer would also be cool (also idea for 'settings'

**Comment by tiphedor** [comment]
This is a 6 year old project, i doubt it still compiles :D I'm definitely not touching that, feel free to fork and try it yourself ! 

As for the store, yeah, it was banned pretty quickly back in the days, for obvious reasons :D
